name: Update index.html

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Use v3 of actions/checkout

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Choose your Python version

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
      shell: bash

    - name: Install dependencies
      run: poetry install

    - name: Run Python script
      run: |
        poetry run python main.py
      working-directory: ${{ github.workspace }}
